Merging forks
theunitedeffort/ueo-watch pull request #6
Opened 2024-11-21 16:16 UTC by ChatanyaSarin

2024-11-22 04:43 UTC, trevorshannon commented
Thanks! I'll try to take a look tomorrow.

2024-11-22 20:34 UTC, trevorshannon commented on resources-jobs/urlwatch.yaml
> +    local_dir: ~/ueo-watch/eligibility/staging
this `eligibility` should be changed to `resources`, as well as below

2024-11-22 20:35 UTC, trevorshannon commented on resources-jobs/urlwatch.yaml
> +    details_url: https://storage.googleapis.com/ueo-changes/housing/report-{datetime}.html
Please replace `housing` with `resources`.

Sorry it has to be done in so many places...I think sometimes YAML supports variables

2024-11-22 21:52 UTC, ChatanyaSarin commented
Hey Trevor, I updated the urlwatch.yaml file. It should be part of the original pull request now. Let me know if there are any other edits you would like for me to make.

2024-11-22 22:03 UTC, trevorshannon requested changes
Great, thanks!  It looks like the urls.yaml file did not get moved over properly.  If you just commit to your `main` branch with the urls.yaml move, we should be all set.

2024-11-22 22:05 UTC, trevorshannon requested changes

2024-11-22 22:05 UTC, trevorshannon commented on resources-jobs/url.yaml
Oh, and this should be urls.yaml (with an `s`)

2024-11-30 18:12 UTC, trevorshannon approved these changes
Thank you!

2024-11-30 18:12 UTC, merged